// ============================================
// 佳乐考研 · 陈妍宇 · Mock数据
// 后续将替换为API调用
// ============================================

import type {
  User,
  Subject,
  StudyTask,
  Resource,
  WrongQuestion,
  Flashcard,
  ChatMessage,
  SchoolInfo,
  DashboardStats,
} from "./types";

// ---- 用户 ----
export const currentUser: User = {
  id: "user_001",
  name: "陈妍宇",
  school: "深圳大学",
  major: "新闻与传播",
  targetSchool: "深圳大学",
  targetMajor: "新闻与传播（MJC）",
  examDate: "2026-12-20",
  createdAt: "2025-01-01",
};

// ---- 四科目标 ----
export const subjects: Subject[] = [
  {
    id: "sub_politics",
    name: "政治",
    code: "101",
    targetScore: 75,
    currentScore: 68,
    progress: 62,
    color: "#ef4444",
    icon: "🏛️",
  },
  {
    id: "sub_english",
    name: "英语二",
    code: "204",
    targetScore: 80,
    currentScore: 72,
    progress: 58,
    color: "#3b82f6",
    icon: "🌐",
  },
  {
    id: "sub_334",
    name: "新闻与传播专业综合能力",
    code: "334",
    targetScore: 120,
    currentScore: 105,
    progress: 71,
    color: "#22c55e",
    icon: "📝",
  },
  {
    id: "sub_440",
    name: "新闻与传播专业基础",
    code: "440",
    targetScore: 120,
    currentScore: 98,
    progress: 65,
    color: "#eab308",
    icon: "📖",
  },
];

// ---- 今日学习任务 ----
export const todayTasks: StudyTask[] = [
  {
    id: "task_001",
    subject: "334",
    title: "新闻采写编评 - 消息写作技巧",
    type: "reading",
    duration: 60,
    completed: true,
    priority: "high",
  },
  {
    id: "task_002",
    subject: "英语二",
    title: "2024年英语二真题阅读 Text 1-2",
    type: "practice",
    duration: 90,
    completed: true,
    priority: "high",
  },
  {
    id: "task_003",
    subject: "440",
    title: "传播学教程 - 议程设置理论",
    type: "reading",
    duration: 60,
    completed: false,
    priority: "high",
  },
  {
    id: "task_004",
    subject: "政治",
    title: "马原 - 唯物辩证法选择题",
    type: "practice",
    duration: 45,
    completed: false,
    priority: "medium",
  },
  {
    id: "task_005",
    subject: "440",
    title: "复议程设置与沉默的螺旋",
    type: "review",
    duration: 30,
    completed: false,
    priority: "medium",
  },
];

// ---- 资料库 ----
export const resources: Resource[] = [
  {
    id: "res_001",
    title: "2024年深圳大学334真题回忆版",
    type: "exam",
    subject: "334",
    chapters: ["新闻采写", "新闻编辑", "新闻评论", "媒介融合"],
    tags: ["真题", "深大", "334"],
    difficulty: 4,
    source: "考研帮/小红书",
    summary: "2024年深大334真题，包含4道简答+2道论述+1道消息写作+1道评论写作",
    uploadDate: "2025-03-15",
    fileSize: "2.3MB",
    pageCount: 4,
    status: "processed",
  },
  {
    id: "res_002",
    title: "传播学教程 - 郭庆光 重点笔记",
    type: "note",
    subject: "440",
    chapters: ["传播学对象", "人类传播", "传播类型", "传播制度", "受众", "效果"],
    tags: ["笔记", "传播学", "郭庆光", "重点"],
    difficulty: 4,
    source: "学姐整理",
    summary: "传播学教程全书重点整理，含核心理论、重要人物、经典实验",
    uploadDate: "2025-02-20",
    fileSize: "15.6MB",
    pageCount: 86,
    status: "processed",
  },
  {
    id: "res_003",
    title: "新闻学概论 - 李良荣 笔记",
    type: "note",
    subject: "440",
    chapters: ["新闻", "新闻业", "新闻自由", "新闻真实", "新闻选择"],
    tags: ["笔记", "新闻学", "李良荣"],
    difficulty: 3,
    source: "学姐整理",
    summary: "新闻学概论第七版全书要点",
    uploadDate: "2025-02-22",
    fileSize: "12.1MB",
    pageCount: 72,
    status: "processed",
  },
  {
    id: "res_004",
    title: "新媒体蓝皮书2024核心观点",
    type: "pdf",
    subject: "334",
    chapters: ["新媒体发展", "媒体融合", "短视频", "直播", "AIGC"],
    tags: ["热点", "新媒体", "蓝皮书"],
    difficulty: 4,
    source: "社科院",
    summary: "2024年中国新媒体发展报告核心观点与热点解读",
    uploadDate: "2025-04-10",
    fileSize: "8.4MB",
    pageCount: 45,
    status: "processed",
  },
  {
    id: "res_005",
    title: "深大新传导师论文合集",
    type: "pdf",
    subject: "334",
    chapters: ["媒介融合", "数据新闻", "计算传播", "城市传播"],
    tags: ["论文", "导师", "深大"],
    difficulty: 5,
    source: "知网",
    summary: "深大传播学院主要导师近3年发表的20篇核心论文",
    uploadDate: "2025-05-01",
    fileSize: "25.3MB",
    pageCount: 156,
    status: "processed",
  },
  {
    id: "res_006",
    title: "2023年深圳大学440真题",
    type: "exam",
    subject: "440",
    chapters: ["传播学", "新闻学", "广告学"],
    tags: ["真题", "深大", "440"],
    difficulty: 4,
    source: "考研帮",
    summary: "2023年深大440真题完整版",
    uploadDate: "2025-03-10",
    fileSize: "1.8MB",
    pageCount: 3,
    status: "processed",
  },
];

// ---- 错题 ----
export const wrongQuestions: WrongQuestion[] = [
  {
    id: "wq_001",
    subject: "440",
    chapter: "传播学效果研究",
    questionType: "short_answer",
    difficulty: 4,
    question: "简述议程设置理论的三个层次及其新媒体环境下的发展",
    userAnswer: "只回答了第一层，缺少属性议程设置和网络议程设置",
    correctAnswer: "三个层次：媒体议程设置（第一层）、属性议程设置（第二层）、网络议程设置（第三层/议程融合理论）",
    explanation: "麦库姆斯和肖提出，议程设置从议题显著性转移到属性显著性，再到网络化传播环境下的议程融合",
    errorReason: "知识点不完整",
    errorCount: 3,
    lastWrongDate: "2025-05-20",
    masteryLevel: 35,
    tags: ["议程设置", "效果研究", "重点理论"],
    source: "模拟考试#3",
  },
  {
    id: "wq_002",
    subject: "440",
    chapter: "传播学基础",
    questionType: "choice",
    difficulty: 3,
    question: "沉默的螺旋提出的学者是？",
    userAnswer: "拉扎斯菲尔德",
    correctAnswer: "伊丽莎白·诺尔-诺依曼（Noelle-Neumann）",
    explanation: "沉默的螺旋由德国传播学者诺依曼于1974年提出",
    errorReason: "人名记忆混淆",
    errorCount: 2,
    lastWrongDate: "2025-05-18",
    masteryLevel: 40,
    tags: ["沉默的螺旋", "传播学者"],
    source: "每日一练",
  },
  {
    id: "wq_003",
    subject: "334",
    chapter: "新闻评论",
    questionType: "essay",
    difficulty: 5,
    question: "请就'算法推荐对新闻专业主义的冲击'写一篇800字评论",
    userAnswer: "论述角度单一，缺乏理论支撑和案例论证",
    correctAnswer: "应从信息茧房、把关人理论变化、新闻价值判断权转移、公共性消解等多角度论述",
    explanation: "高分评论需要：明确论点→理论支撑→案例论证→辩证分析→建设性意见",
    errorReason: "论证不充分",
    errorCount: 2,
    lastWrongDate: "2025-05-15",
    masteryLevel: 30,
    tags: ["评论写作", "算法", "新闻专业主义"],
    source: "模拟考试#2",
  },
  {
    id: "wq_004",
    subject: "英语二",
    chapter: "阅读理解",
    questionType: "choice",
    difficulty: 3,
    question: "2024 Text2 - 作者对数字鸿沟的态度是？",
    userAnswer: "optimistic",
    correctAnswer: "cautiously optimistic",
    explanation: "作者承认数字鸿沟在缩小，但仍对深层不平等表示担忧，态度是谨慎乐观而非完全乐观",
    errorReason: "过度简化作者态度",
    errorCount: 4,
    lastWrongDate: "2025-05-22",
    masteryLevel: 25,
    tags: ["态度题", "阅读技巧"],
    source: "真题练习",
  },
  {
    id: "wq_005",
    subject: "政治",
    chapter: "马原",
    questionType: "choice",
    difficulty: 3,
    question: "唯物辩证法的实质和核心是？",
    userAnswer: "否定之否定规律",
    correctAnswer: "对立统一规律（矛盾规律）",
    explanation: "对立统一规律揭示了事物发展的源泉和动力，是唯物辩证法的实质和核心",
    errorReason: "哲学规律记忆混淆",
    errorCount: 2,
    lastWrongDate: "2025-05-19",
    masteryLevel: 50,
    tags: ["马原", "辩证法", "核心概念"],
    source: "1000题",
  },
];

// ---- 闪卡 ----
export const flashcards: Flashcard[] = [
  {
    id: "card_001",
    front: "议程设置理论",
    back: "麦库姆斯和肖（1972）提出。大众媒介可以通过反复报道来赋予议题不同程度的显著性，影响公众对议题重要性的判断。三个层次：议题显著性→属性显著性→网络议程设置。",
    subject: "440",
    type: "concept",
    difficulty: 4,
    stability: 2.5,
    difficulty_factor: 5.0,
    elapsed_days: 3,
    scheduled_days: 5,
    reps: 4,
    lapses: 1,
    state: "review",
    due: "2025-05-28",
    last_review: "2025-05-23",
  },
  {
    id: "card_002",
    front: "沉默的螺旋理论",
    back: "诺依曼（1974）提出。人们在表达观点时会观察舆论环境，如果发现自己的观点属于少数派，出于被孤立的恐惧，会倾向于沉默。优势意见越来越强，劣势意见越来越弱，形成螺旋。",
    subject: "440",
    type: "concept",
    difficulty: 3,
    stability: 3.0,
    difficulty_factor: 4.5,
    elapsed_days: 2,
    scheduled_days: 7,
    reps: 5,
    lapses: 0,
    state: "review",
    due: "2025-05-30",
    last_review: "2025-05-23",
  },
  {
    id: "card_003",
    front: "把关人理论（Gatekeeping）",
    back: "卢因（1947）提出。信息在传播过程中需要经过把关人的筛选和过滤。传统媒体时代编辑是主要把关人，新媒体时代把关权转移至算法、平台和用户，呈现'去中心化把关'特征。",
    subject: "440",
    type: "concept",
    difficulty: 3,
    stability: 4.0,
    difficulty_factor: 4.0,
    elapsed_days: 1,
    scheduled_days: 10,
    reps: 6,
    lapses: 0,
    state: "review",
    due: "2025-06-02",
    last_review: "2025-05-23",
  },
  {
    id: "card_004",
    front: "使用与满足理论",
    back: "卡茨（1974）提出。受众是主动的，基于特定需求选择和使用媒介来获得满足。四种需求：认知需求、情感需求、个人整合需求、社会整合需求。强调受众的主动性。",
    subject: "440",
    type: "concept",
    difficulty: 3,
    stability: 5.0,
    difficulty_factor: 3.5,
    elapsed_days: 0,
    scheduled_days: 14,
    reps: 7,
    lapses: 0,
    state: "review",
    due: "2025-06-06",
    last_review: "2025-05-23",
  },
  {
    id: "card_005",
    front: "新闻价值五要素",
    back: "①时新性：事件发生的时间近、内容新\n②重要性：影响范围大、涉及人数多\n③显著性：人物、地点的知名度\n④接近性：地理或心理上的接近\n⑤趣味性：人情味、新奇性",
    subject: "440",
    type: "concept",
    difficulty: 2,
    stability: 6.0,
    difficulty_factor: 3.0,
    elapsed_days: 0,
    scheduled_days: 21,
    reps: 8,
    lapses: 0,
    state: "review",
    due: "2025-06-13",
    last_review: "2025-05-23",
  },
  {
    id: "card_006",
    front: "框架理论（Framing Theory）",
    back: "戈夫曼（1974）提出框架概念，恩特曼引入传播学。媒体通过选择、强调和排除来建构报道框架，影响受众对事件的理解。与议程设置的区别：议程设置告诉人们'想什么'，框架理论告诉人们'怎么想'。",
    subject: "440",
    type: "concept",
    difficulty: 4,
    stability: 1.5,
    difficulty_factor: 6.0,
    elapsed_days: 5,
    scheduled_days: 3,
    reps: 2,
    lapses: 2,
    state: "relearning",
    due: "2025-05-25",
    last_review: "2025-05-20",
  },
  {
    id: "card_007",
    front: "知识沟假说",
    back: "蒂奇诺等（1970）提出。随着大众传播的信息量增加，社会经济地位较高的人获取知识的速度快于地位低的人，两者之间的知识差距会扩大而非缩小。影响因素：传播技能、信息储备、社会交往、选择性接触。",
    subject: "440",
    type: "concept",
    difficulty: 4,
    stability: 2.0,
    difficulty_factor: 5.5,
    elapsed_days: 4,
    scheduled_days: 4,
    reps: 3,
    lapses: 1,
    state: "review",
    due: "2025-05-27",
    last_review: "2025-05-22",
  },
  {
    id: "card_008",
    front: "培养理论（Cultivation Theory）",
    back: "格伯纳（1960s）提出。大众传媒通过长期的、潜移默化的影响，会塑造受众对现实世界的认知。重度电视观众的世界观会更接近电视所呈现的'符号现实'。分为共鸣效果和第一级信念/第二级信念。",
    subject: "440",
    type: "concept",
    difficulty: 3,
    stability: 3.5,
    difficulty_factor: 4.0,
    elapsed_days: 2,
    scheduled_days: 8,
    reps: 4,
    lapses: 0,
    state: "review",
    due: "2025-05-31",
    last_review: "2025-05-23",
  },
];

// ---- 院校信息 ----
export const schoolInfo: SchoolInfo = {
  name: "深圳大学",
  major: "新闻与传播（MJC）",
  code: "055200",
  department: "传播学院",
  examSubjects: ["101 思想政治理论", "204 英语二", "334 新闻与传播专业综合能力", "440 新闻与传播专业基础"],
  scoreLines: [
    { year: 2025, total: 367, politics: 55, english: 55, major1: 83, major2: 83, enrolled: 35, applicants: 480 },
    { year: 2024, total: 363, politics: 54, english: 54, major1: 81, major2: 81, enrolled: 30, applicants: 450 },
    { year: 2023, total: 365, politics: 54, english: 54, major1: 81, major2: 81, enrolled: 28, applicants: 420 },
    { year: 2022, total: 367, politics: 56, english: 56, major1: 84, major2: 84, enrolled: 25, applicants: 380 },
    { year: 2021, total: 355, politics: 53, english: 53, major1: 80, major2: 80, enrolled: 22, applicants: 320 },
  ],
  admissionRatio: "约14:1",
  referenceBooks: [
    "《新闻学概论》李良荣",
    "《传播学教程》郭庆光",
    "《网络传播概论》彭兰",
    "《新闻采访学》蓝鸿文",
    "《新闻写作教程》刘明华",
    "《新闻编辑学》蔡雯",
    "《新闻评论教程》马少华",
    "《广告学概论》陈培爱",
    "《公共关系学》居延安",
    "《媒介经营与管理》谢新洲",
  ],
  difficultyRating: 4,
  trend: "rising",
};

// ---- 仪表盘统计 ----
export const dashboardStats: DashboardStats = {
  totalStudyHours: 486,
  todayStudyMinutes: 245,
  weeklyStudyMinutes: [420, 380, 450, 390, 510, 480, 245],
  completionRate: 78,
  mockExamAverage: 328,
  predictedScore: 358,
  weakPoints: ["新闻评论写作", "传播学效果研究", "英语阅读态度题", "政治经济学部分"],
  strongPoints: ["新闻学基础理论", "传播学基础概念", "新闻采写", "英语完形填空"],
  streakDays: 34,
  totalCards: 156,
  dueCards: 23,
  wrongQuestions: 38,
  resourcesCount: 47,
};

// ---- AI对话示例 ----
export const chatHistory: ChatMessage[] = [
  {
    id: "msg_001",
    role: "user",
    content: "议程设置理论和框架理论有什么区别？考试怎么答？",
    timestamp: "2025-05-23T10:30:00Z",
  },
  {
    id: "msg_002",
    role: "assistant",
    content: `## 议程设置 vs 框架理论 对比

### 核心区别

| 维度 | 议程设置 | 框架理论 |
|------|----------|----------|
| **核心命题** | 媒体告诉人们"想什么" | 媒体告诉人们"怎么想" |
| **关注层面** | 议题的显著性 | 议题的解读方式 |
| **理论渊源** | 李普曼→麦库姆斯&肖 | 戈夫曼→恩特曼 |
| **分析层次** | 议题/属性层面 | 文本/认知层面 |

### 深大334/440答题模板

**1. 概念界定**（2分）
分别用1-2句话定义两个理论

**2. 对比分析**（6分）
从研究对象、核心机制、分析层次、新媒体适用性四个角度对比

**3. 案例论证**（4分）
以具体新闻事件为例，说明两个理论如何同时作用

**4. 总结提升**（3分）
指出两者在新媒体环境下的发展与融合趋势

> 💡 **深大考情提示**：这类对比分析题在深大440中出现频率很高，建议准备10组以上经典理论对比。

### 相关练习建议
- 完成「传播学效果研究」专题错题重做
- 复习框架理论在新媒体环境下的发展`,
    timestamp: "2025-05-23T10:30:30Z",
    sources: ["传播学教程 郭庆光", "网络传播概论 彭兰", "2024深大440真题"],
  },
];

// ---- 热点专题 ----
export const hotspotTopics = [
  { id: "hs_001", title: "AIGC与新闻生产变革", heat: 95, subject: "334/440", status: "已整理" },
  { id: "hs_002", title: "短视频平台算法推荐机制", heat: 88, subject: "334", status: "已整理" },
  { id: "hs_003", title: "媒体深度融合与县级融媒体", heat: 85, subject: "334", status: "复习中" },
  { id: "hs_004", title: "网络舆论与群体极化", heat: 82, subject: "440", status: "已整理" },
  { id: "hs_005", title: "数据新闻与计算传播学", heat: 78, subject: "334", status: "待整理" },
  { id: "hs_006", title: "国际传播与话语权建设", heat: 90, subject: "334/440", status: "复习中" },
  { id: "hs_007", title: "平台经济与反垄断", heat: 75, subject: "政治", status: "待整理" },
  { id: "hs_008", title: "数字鸿沟与信息公平", heat: 72, subject: "440", status: "已整理" },
];

// ---- 社区帖子 ----
export const communityPosts = [
  {
    id: "post_001",
    author: "深大新传小王",
    avatar: "🧑‍🎓",
    title: "深圳大学新传MJC初试第一经验分享",
    content: "分享我的备考时间线、参考书使用顺序、以及334和440的答题技巧...",
    likes: 234,
    comments: 56,
    tags: ["经验帖", "深大", "MJC"],
    date: "2025-05-10",
  },
  {
    id: "post_002",
    author: "新传考研人",
    avatar: "👩‍💻",
    title: "传播学十大必背理论口诀（附对比表）",
    content: "议程设置、沉默螺旋、培养理论、使用满足、知识沟...用口诀记理论不容易混",
    likes: 189,
    comments: 34,
    tags: ["笔记", "传播学", "口诀"],
    date: "2025-05-15",
  },
  {
    id: "post_003",
    author: "25届上岸学姐",
    avatar: "🎓",
    title: "深大新传导师选择避坑指南",
    content: "传播学院导师风格各异，选导师不仅看研究方向，还要看培养风格和毕业要求...",
    likes: 156,
    comments: 42,
    tags: ["导师", "深大", "复试"],
    date: "2025-05-08",
  },
];