import { Hono } from "hono";
import type { Env, Variables } from "./env";
import { all, asNumber, clamp, dateAfter, first, id, likePattern, now, parseRow, run, safeJson, serializeJson } from "./db";

export const learningRoutes = new Hono<{ Bindings: Env; Variables: Variables }>();

function parseCard(row: Record<string, any>) { return row; }
function parsePlan(row: Record<string, any>) { return parseRow(row, ["subjects", "phases", "daily_plan"]); }
function parseExam(row: Record<string, any>) { return parseRow(row, ["questions", "answers", "analysis"]); }

// Flashcards
learningRoutes.get("/flashcards/due", async (c) => {
  const user = c.get("user"); const limit = asNumber(c.req.query("limit"), 20, 1, 100); const subject = c.req.query("subject");
  let sql = "SELECT * FROM flashcards WHERE user_id=? AND due_date<=CURRENT_TIMESTAMP"; const params: unknown[] = [user.id];
  if (subject) { sql += " AND subject=?"; params.push(subject); } sql += " ORDER BY due_date LIMIT ?"; params.push(limit);
  const cards = await all<Record<string, any>>(c.env.DB, sql, params); return c.json({ cards, total: cards.length });
});
learningRoutes.get("/flashcards/stats", async (c) => {
  const user = c.get("user");
  const stats = await first<Record<string, any>>(c.env.DB, "SELECT COUNT(*) total,SUM(CASE WHEN due_date<=CURRENT_TIMESTAMP THEN 1 ELSE 0 END) due,SUM(CASE WHEN review_count>0 THEN 1 ELSE 0 END) reviewed FROM flashcards WHERE user_id=?", [user.id]);
  const today = await first<{ count: number }>(c.env.DB, "SELECT COUNT(*) count FROM flashcard_reviews fr JOIN flashcards f ON f.id=fr.card_id WHERE f.user_id=? AND date(fr.created_at)=date('now')", [user.id]);
  const subjects = await all<{ subject: string; count: number }>(c.env.DB, "SELECT COALESCE(subject,'未分类') subject,COUNT(*) count FROM flashcards WHERE user_id=? GROUP BY subject", [user.id]);
  return c.json({ total: stats?.total || 0, due: stats?.due || 0, reviewed: stats?.reviewed || 0, reviewed_today: today?.count || 0, by_subject: Object.fromEntries(subjects.map((x) => [x.subject, x.count])) });
});
learningRoutes.get("/flashcards", async (c) => {
  const user = c.get("user"); const subject = c.req.query("subject");
  const rows = subject ? await all(c.env.DB, "SELECT * FROM flashcards WHERE user_id=? AND subject=? ORDER BY created_at DESC", [user.id, subject]) : await all(c.env.DB, "SELECT * FROM flashcards WHERE user_id=? ORDER BY created_at DESC", [user.id]);
  return c.json({ cards: rows, total: rows.length });
});
learningRoutes.post("/flashcards", async (c) => {
  const user = c.get("user"); const body = await c.req.json<Record<string, any>>();
  if (!body.front || !body.back) return c.json({ detail: "卡片正反面不能为空" }, 400); const cardId = id("fc");
  await run(c.env.DB, "INSERT INTO flashcards (id,user_id,front,back,subject,topic,card_type,due_date) VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP)", [cardId,user.id,body.front,body.back,body.subject||null,body.topic||null,body.card_type||"qa"]);
  const card = await first(c.env.DB, "SELECT * FROM flashcards WHERE id=?", [cardId]); return c.json(card, 201);
});
learningRoutes.post("/flashcards/generate", async (c) => {
  const user = c.get("user"); const body = await c.req.json<Record<string, any>>(); const count = asNumber(String(body.count || 10), 10, 1, 30); const subject = body.subject || "440"; const topic = String(body.topic || "").trim();
  const pattern = topic ? likePattern(topic) : "%";
  const points = await all<Record<string, any>>(c.env.DB, "SELECT title,summary,content FROM knowledge_points WHERE subject_id=? AND (owner_id IS NULL OR owner_id=?) AND (title LIKE ? OR content LIKE ?) ORDER BY RANDOM() LIMIT ?", [subject,user.id,pattern,pattern,count]);
  const created = [];
  for (const point of points) { const cardId=id("fc"); const back=point.summary || String(point.content).slice(0,600); await run(c.env.DB,"INSERT INTO flashcards (id,user_id,front,back,subject,topic,due_date) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP)",[cardId,user.id,point.title,back,subject,topic||null]); created.push({id:cardId,front:point.title,back,subject,topic}); }
  return c.json({ cards: created, count: created.length, message: `已生成 ${created.length} 张闪卡` });
});
learningRoutes.post("/flashcards/:cardId/review", async (c) => {
  const user = c.get("user"); const body = await c.req.json<Record<string, any>>(); const rating = asNumber(String(body.rating),0); if (![1,2,3,4].includes(rating)) return c.json({detail:"评分必须在 1-4 之间"},400);
  const card = await first<Record<string, any>>(c.env.DB,"SELECT * FROM flashcards WHERE id=? AND user_id=?",[c.req.param("cardId"),user.id]); if(!card) return c.json({detail:"闪卡不存在"},404);
  const stability=clamp(Number(card.stability||2.5)*({1:.35,2:.8,3:1.4,4:2.2} as Record<number,number>)[rating]+.3,0.2,365); const days=rating===1?1:Math.max(1,Math.round(stability*(rating===4?1.5:rating===3?1:.5))); const due=dateAfter(days);
  await c.env.DB.batch([
    c.env.DB.prepare("UPDATE flashcards SET stability=?,difficulty=?,due_date=?,last_review=CURRENT_TIMESTAMP,review_count=review_count+1,lapse_count=lapse_count+? WHERE id=?").bind(stability,clamp(Number(card.difficulty||.5)+(3-rating)*.05,.1,.95),due,rating===1?1:0,card.id),
    c.env.DB.prepare("INSERT INTO flashcard_reviews (id,card_id,rating,stability_before,stability_after) VALUES (?,?,?,?,?)").bind(id("fcr"),card.id,rating,card.stability||2.5,stability),
  ]);
  return c.json({message:"复习完成",next_review:due,interval_days:days,stability});
});

// Study sessions
learningRoutes.post("/study-sessions/start", async (c) => { const user=c.get("user"); const body=await c.req.json<Record<string,any>>(); const sessionId=id("ss"); await run(c.env.DB,"INSERT INTO study_sessions (id,user_id,knowledge_point_id,subject,activity_type,start_time) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP)",[sessionId,user.id,body.knowledge_point_id||null,body.subject||null,body.activity_type||"focus"]); return c.json({id:sessionId,session_id:sessionId,start_time:now()},201); });
learningRoutes.post("/study-sessions/:sessionId/stop", async (c) => { const user=c.get("user"); const session=await first<Record<string,any>>(c.env.DB,"SELECT * FROM study_sessions WHERE id=? AND user_id=?",[c.req.param("sessionId"),user.id]); if(!session)return c.json({detail:"学习会话不存在"},404); const body=await c.req.json<Record<string,any>>().catch(()=>({} as Record<string,any>)); const start=new Date(String(session.start_time).replace(" ","T")+"Z").getTime(); const duration=Math.max(0,Math.round(Number(body.duration_seconds)||((Date.now()-start)/1000))); await run(c.env.DB,"UPDATE study_sessions SET end_time=CURRENT_TIMESTAMP,duration_seconds=? WHERE id=?",[duration,session.id]); await run(c.env.DB,"INSERT INTO study_records (id,user_id,activity_type,subject,duration_minutes,details) VALUES (?,?,?,?,?,?)",[id("sr"),user.id,session.activity_type,session.subject||null,Math.round(duration/60),serializeJson({session_id:session.id})]); return c.json({id:session.id,duration_seconds:duration,status:"completed"}); });
learningRoutes.get("/study-sessions/stats", async (c) => { const user=c.get("user"); const row=await first<Record<string,any>>(c.env.DB,"SELECT COALESCE(SUM(CASE WHEN date(created_at)=date('now') THEN duration_seconds ELSE 0 END),0) today,COALESCE(SUM(CASE WHEN created_at>=datetime('now','-7 days') THEN duration_seconds ELSE 0 END),0) week,COALESCE(SUM(duration_seconds),0) total FROM study_sessions WHERE user_id=?",[user.id]); const days=await all<{day:string}>(c.env.DB,"SELECT DISTINCT date(created_at) day FROM study_sessions WHERE user_id=? ORDER BY day DESC LIMIT 60",[user.id]); let streak=0; let cursor=new Date(); for(const d of days){const expected=cursor.toISOString().slice(0,10); if(d.day===expected){streak++;cursor.setUTCDate(cursor.getUTCDate()-1)}else if(streak===0){cursor.setUTCDate(cursor.getUTCDate()-1);if(d.day===cursor.toISOString().slice(0,10)){streak++;cursor.setUTCDate(cursor.getUTCDate()-1)}else break}else break} return c.json({today_minutes:Math.round((row?.today||0)/60),week_minutes:Math.round((row?.week||0)/60),total_minutes:Math.round((row?.total||0)/60),streak_days:streak}); });

// Wrong questions
learningRoutes.get("/wrong-questions/analysis", async (c) => { const user=c.get("user"); const bySubject=await all(c.env.DB,"SELECT subject,COUNT(*) count,AVG(mastery) avg_mastery FROM wrong_questions WHERE user_id=? GROUP BY subject",[user.id]); const byType=await all(c.env.DB,"SELECT COALESCE(error_type,'未分类') error_type,COUNT(*) count FROM wrong_questions WHERE user_id=? GROUP BY error_type",[user.id]); const total=await first<{count:number}>(c.env.DB,"SELECT COUNT(*) count FROM wrong_questions WHERE user_id=?",[user.id]); return c.json({total:total?.count||0,by_subject:bySubject,by_error_type:byType}); });
learningRoutes.get("/wrong-questions", async (c) => { const user=c.get("user"); const subject=c.req.query("subject"); const rows=subject?await all(c.env.DB,"SELECT * FROM wrong_questions WHERE user_id=? AND subject=? ORDER BY created_at DESC",[user.id,subject]):await all(c.env.DB,"SELECT * FROM wrong_questions WHERE user_id=? ORDER BY created_at DESC",[user.id]); return c.json({questions:rows,total:rows.length}); });
learningRoutes.post("/wrong-questions", async (c)=>{const user=c.get("user");const b=await c.req.json<Record<string,any>>();if(!b.content||!b.subject)return c.json({detail:"题目和科目不能为空"},400);const qid=id("wq");await run(c.env.DB,"INSERT INTO wrong_questions (id,user_id,content,subject,topic,answer,user_answer,error_type,error_analysis,next_review) VALUES (?,?,?,?,?,?,?,?,?,?)",[qid,user.id,b.content,b.subject,b.topic||null,b.answer||null,b.user_answer||null,b.error_type||null,b.error_analysis||null,dateAfter(1)]);return c.json(await first(c.env.DB,"SELECT * FROM wrong_questions WHERE id=?",[qid]),201)});
learningRoutes.put("/wrong-questions/:id",async(c)=>{const user=c.get("user");const b=await c.req.json<Record<string,any>>();const allowed=["content","subject","topic","answer","user_answer","error_type","error_analysis","mastery","next_review"];const keys=allowed.filter(k=>b[k]!==undefined);if(keys.length)await run(c.env.DB,`UPDATE wrong_questions SET ${keys.map(k=>`${k}=?`).join(",")} WHERE id=? AND user_id=?`,[...keys.map(k=>b[k]),c.req.param("id"),user.id]);return c.json({id:c.req.param("id"),status:"updated"})});
learningRoutes.delete("/wrong-questions/:id",async(c)=>{const user=c.get("user");await run(c.env.DB,"DELETE FROM wrong_questions WHERE id=? AND user_id=?",[c.req.param("id"),user.id]);return c.json({status:"deleted"})});

// Study plans: current UI treats each row as a task, stored in daily_plan JSON for schema compatibility.
learningRoutes.get("/study-plans",async(c)=>{const user=c.get("user");const date=c.req.query("date");let rows:Record<string,any>[];if(date)rows=await all(c.env.DB,"SELECT * FROM study_plans WHERE user_id=? AND target_date=? ORDER BY created_at",[user.id,date]);else rows=await all(c.env.DB,"SELECT * FROM study_plans WHERE user_id=? ORDER BY target_date,created_at",[user.id]);return c.json({plans:rows.map(parsePlan),total:rows.length})});
learningRoutes.post("/study-plans",async(c)=>{const user=c.get("user");const b=await c.req.json<Record<string,any>>();const pid=id("sp");const task={title:b.title||"学习任务",subject:b.subject||"440",duration:Number(b.duration||60),priority:b.priority||"medium",date:b.date||new Date().toISOString().slice(0,10),completed:false};await run(c.env.DB,"INSERT INTO study_plans (id,user_id,target_date,daily_hours,subjects,daily_plan,status) VALUES (?,?,?,?,?,?,?)",[pid,user.id,task.date,task.duration,task.subject,serializeJson(task),"active"]);return c.json({id:pid,...task,status:"active"},201)});
learningRoutes.put("/study-plans/:id/toggle",async(c)=>{const user=c.get("user");const row=await first<Record<string,any>>(c.env.DB,"SELECT * FROM study_plans WHERE id=? AND user_id=?",[c.req.param("id"),user.id]);if(!row)return c.json({detail:"计划不存在"},404);const task=safeJson<Record<string,any>>(row.daily_plan,{});task.completed=!task.completed;await run(c.env.DB,"UPDATE study_plans SET daily_plan=?,status=? WHERE id=?",[serializeJson(task),task.completed?"completed":"active",row.id]);return c.json({id:row.id,...task,status:task.completed?"completed":"active"})});
learningRoutes.delete("/study-plans/:id",async(c)=>{const user=c.get("user");await run(c.env.DB,"DELETE FROM study_plans WHERE id=? AND user_id=?",[c.req.param("id"),user.id]);return c.json({status:"deleted"})});
learningRoutes.post("/study-plan/generate",async(c)=>{const b=await c.req.json<Record<string,any>>();const days=asNumber(String(b.days||7),7,1,30);const hours=asNumber(String(b.hours_per_day||b.daily_hours||6),6,1,14);const subjects=["440 新闻传播专业基础","334 新闻传播综合能力","英语","政治"];const plan=Array.from({length:days},(_,i)=>({day:i+1,focus:i%3===0?"理解框架":i%3===1?"真题训练":"复习巩固",tasks:subjects.slice(0,Math.min(4,Math.max(2,Math.round(hours/2)))).map((subject,j)=>({title:["核心知识精读与框架整理","专题真题作答与复盘","闪卡复习与主动回忆","错题归因与二次作答"][(i+j)%4],subject:subject.split(" ")[0],duration:Math.round(hours*60/Math.min(4,Math.max(2,Math.round(hours/2)))),priority:j===0?"high":"medium"}))}));return c.json({plan,days,hours_per_day:hours,source:"rule_engine"})});

// Exams and question bank generation
learningRoutes.get("/exams",async(c)=>{const user=c.get("user");const rows=(await all<Record<string,any>>(c.env.DB,"SELECT * FROM exams WHERE user_id=? ORDER BY created_at DESC",[user.id])).map(parseExam);return c.json({exams:rows,total:rows.length})});
learningRoutes.post("/exams/save",async(c)=>{const user=c.get("user");const b=await c.req.json<Record<string,any>>();const eid=id("ex");await run(c.env.DB,"INSERT INTO exams (id,user_id,subject,difficulty,total_questions,total_score,score,accuracy,time_limit,time_used,status,questions,answers,analysis,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)",[eid,user.id,b.subject||"综合",b.difficulty||"medium",b.total_questions||safeJson<any[]>(b.questions,[]).length,b.total_score||0,b.score||0,b.accuracy||0,b.time_limit||null,b.time_used||null,"completed",serializeJson(b.questions),serializeJson(b.answers),serializeJson(b.analysis)]);return c.json({id:eid,status:"saved"},201)});
learningRoutes.get("/exams/:id",async(c)=>{const user=c.get("user");const row=await first<Record<string,any>>(c.env.DB,"SELECT * FROM exams WHERE id=? AND user_id=?",[c.req.param("id"),user.id]);if(!row)return c.json({detail:"考试记录不存在"},404);return c.json(parseExam(row))});
learningRoutes.post("/exam/generate",async(c)=>{const b=await c.req.json<Record<string,any>>();const count=asNumber(String(b.count||10),10,1,50);const subject=b.subject||null;const difficulty=String(b.difficulty||"");let sql="SELECT * FROM question_bank WHERE 1=1";const params:unknown[]=[];if(subject){sql+=" AND subject=?";params.push(subject)}if(["easy","medium","hard"].includes(difficulty)){sql+=" AND difficulty=?";params.push(difficulty)}sql+=" ORDER BY RANDOM() LIMIT ?";params.push(count);const rows=(await all<Record<string,any>>(c.env.DB,sql,params)).map(r=>parseRow(r,["options","tags"]));return c.json({questions:rows,count:rows.length,subject:subject||"综合",difficulty:difficulty||"mixed",source:"question_bank"})});

// Dashboard
learningRoutes.get("/dashboard/stats",async(c)=>{const u=c.get("user");const [today,totals,due,performance,knowledge,vocabulary]=await Promise.all([
 first<Record<string,any>>(c.env.DB,"SELECT (SELECT COUNT(*) FROM messages m JOIN conversations cv ON cv.id=m.conversation_id WHERE cv.user_id=? AND date(m.created_at)=date('now')) chat_messages,(SELECT COUNT(*) FROM flashcard_reviews fr JOIN flashcards f ON f.id=fr.card_id WHERE f.user_id=? AND date(fr.created_at)=date('now')) flashcards_reviewed,(SELECT COUNT(*) FROM study_records WHERE user_id=? AND date(created_at)=date('now')) total_activities,(SELECT COUNT(*) FROM exams WHERE user_id=? AND date(completed_at)=date('now')) exams_taken,(SELECT COALESCE(SUM(duration_seconds),0)/60 FROM study_sessions WHERE user_id=? AND date(created_at)=date('now')) study_minutes",[u.id,u.id,u.id,u.id,u.id]),
 first<Record<string,any>>(c.env.DB,"SELECT (SELECT COUNT(*) FROM conversations WHERE user_id=?) conversations,(SELECT COUNT(*) FROM messages m JOIN conversations cv ON cv.id=m.conversation_id WHERE cv.user_id=?) messages,(SELECT COUNT(*) FROM flashcards WHERE user_id=?) flashcards,(SELECT COUNT(*) FROM wrong_questions WHERE user_id=?) wrong_questions,(SELECT COUNT(*) FROM exams WHERE user_id=?) exams",[u.id,u.id,u.id,u.id,u.id]),
 first<Record<string,any>>(c.env.DB,"SELECT (SELECT COUNT(*) FROM flashcards WHERE user_id=? AND due_date<=CURRENT_TIMESTAMP) flashcards,(SELECT COUNT(*) FROM wrong_questions WHERE user_id=? AND next_review<=CURRENT_TIMESTAMP) wrong_questions,(SELECT COUNT(*) FROM knowledge_reviews WHERE user_id=? AND due_date<=CURRENT_TIMESTAMP) knowledge_reviews",[u.id,u.id,u.id]),
 first<Record<string,any>>(c.env.DB,"SELECT COALESCE((SELECT AVG(accuracy) FROM exams WHERE user_id=? AND status='completed'),0) exam_avg_accuracy,COUNT(DISTINCT date(created_at)) streak_days FROM study_sessions WHERE user_id=? AND created_at>=datetime('now','-30 days')",[u.id,u.id]),
 first<Record<string,any>>(c.env.DB,"SELECT (SELECT COUNT(*) FROM knowledge_points WHERE owner_id IS NULL OR owner_id=?) total_points,(SELECT COUNT(*) FROM knowledge_reviews WHERE user_id=?) reviewed,(SELECT COUNT(*) FROM knowledge_reviews WHERE user_id=? AND due_date<=CURRENT_TIMESTAMP) due",[u.id,u.id,u.id]),
 first<Record<string,any>>(c.env.DB,"SELECT (SELECT COUNT(*) FROM vocabulary WHERE user_id IS NULL OR user_id=?) total,(SELECT COUNT(*) FROM vocabulary_reviews WHERE user_id=? AND stability>=7) mastered",[u.id,u.id]),
 ]);return c.json({today:today||{},totals:totals||{},due:due||{},performance:performance||{},knowledge:knowledge||{},vocabulary:vocabulary||{}})});

// Recommendations and prediction use real user activity without paid AI.
learningRoutes.get("/recommendations/weak-points",async(c)=>{const u=c.get("user");const limit=asNumber(c.req.query("limit"),5,1,30);const rows=await all(c.env.DB,"SELECT kp.id,kp.title,kp.subject_id,kp.chapter_id,kp.importance,kr.stability,kr.difficulty,kr.lapse_count FROM knowledge_reviews kr JOIN knowledge_points kp ON kp.id=kr.knowledge_point_id WHERE kr.user_id=? ORDER BY kr.lapse_count DESC,kr.stability ASC LIMIT ?",[u.id,limit]);return c.json({weak_points:rows,total:rows.length})});
learningRoutes.get("/recommendations/study-plan",async(c)=>{const days=asNumber(c.req.query("days"),7,1,30);const weak=(await all<Record<string,any>>(c.env.DB,"SELECT kp.id,kp.title,kp.subject_id FROM knowledge_points kp LEFT JOIN knowledge_reviews kr ON kr.knowledge_point_id=kp.id AND kr.user_id=? WHERE (kp.owner_id IS NULL OR kp.owner_id=?) ORDER BY COALESCE(kr.stability,0) ASC,kp.importance='high' DESC LIMIT ?",[c.get("user").id,c.get("user").id,days*3]));return c.json({days,plan:Array.from({length:days},(_,i)=>({day:i+1,date:new Date(Date.now()+i*86400000).toISOString().slice(0,10),items:weak.slice(i*3,i*3+3)}))})});
learningRoutes.get("/recommendations",async(c)=>{const limit=asNumber(c.req.query("limit"),10,1,30);const rows=await all(c.env.DB,"SELECT kp.id,kp.title,kp.subject_id,kp.chapter_id,kp.summary,kp.importance,COALESCE(kr.stability,0) stability FROM knowledge_points kp LEFT JOIN knowledge_reviews kr ON kr.knowledge_point_id=kp.id AND kr.user_id=? WHERE (kp.owner_id IS NULL OR kp.owner_id=?) ORDER BY CASE WHEN kr.due_date<=CURRENT_TIMESTAMP THEN 0 WHEN kr.id IS NULL THEN 1 ELSE 2 END,kp.importance='high' DESC,RANDOM() LIMIT ?",[c.get("user").id,c.get("user").id,limit]);return c.json({recommendations:rows.map((r:any)=>({...r,reason:Number(r.stability)===0?"尚未学习，建议建立首次记忆":"已到复习窗口"})),total:rows.length})});
learningRoutes.get("/predictions/trend",async(c)=>{const days=asNumber(c.req.query("days"),30,1,180);const rows=await all<Record<string,any>>(c.env.DB,"SELECT date(created_at) date,COALESCE(SUM(duration_seconds),0)/60 study_minutes,COUNT(*) sessions FROM study_sessions WHERE user_id=? AND created_at>=datetime('now',?) GROUP BY date(created_at) ORDER BY date",[c.get("user").id,`-${days} days`]);return c.json({trend:rows.map(r=>({...r,score:Math.min(100,Math.round(Number(r.study_minutes||0)/3+Number(r.sessions||0)*5))})),days})});
learningRoutes.get("/predictions/score",async(c)=>{const u=c.get("user");const exam=await first<Record<string,any>>(c.env.DB,"SELECT AVG(accuracy) accuracy,COUNT(*) count FROM exams WHERE user_id=?",[u.id]);const activity=await first<Record<string,any>>(c.env.DB,"SELECT COALESCE(SUM(duration_seconds),0)/3600 hours FROM study_sessions WHERE user_id=? AND created_at>=datetime('now','-30 days')",[u.id]);const accuracy=Number(exam?.accuracy||0);const score=clamp(Math.round((accuracy||50)*.75+Math.min(25,Number(activity?.hours||0))),0,100);return c.json({predicted_score:score,confidence:Number(exam?.count||0)>=3?"medium":"low",basis:{exam_accuracy:accuracy,study_hours_30d:Number(activity?.hours||0),exam_count:Number(exam?.count||0)}})});
